name: Build create-disp

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ pkg-config libdrm-dev libsystemd-dev

      - name: Create build directory
        run: mkdir -p build

      - name: Configure with CMake
        run: |
          cd build
          cmake ..

      - name: Build project
        run: |
          cd build
          cmake --build .

      - name: Upload binary artifact
        uses: actions/upload-artifact@v3
        with:
          name: create-disp-binary
          path: build/create-disp
